package mapreduceapps

//
// a word-count application for MapReduce.
//

import (
	"strconv"
	"strings"
	"time"

	"m4/mapreduce"
)

// The map function is called once for each file of input.
// This map function just returns 1 for each file
func MapEarlyExit(filename string, contents string) []mapreduce.KeyValue {
	kva := []mapreduce.KeyValue{}
	kva = append(kva, mapreduce.KeyValue{Key: filename, Value: "1"})
	return kva
}

// The reduce function is called once for each key generated by the
// map tasks, with a list of all the values created for that key by
// any map task.
func ReduceEarlyExit(key string, values []string) string {
	// some reduce tasks sleep for a long time; potentially seeing if
	// a worker will accidentally exit early
	if strings.Contains(key, "sherlock") || strings.Contains(key, "tom") {
		time.Sleep(time.Duration(2 * time.Second))
	}
	// return the number of occurrences of this file.
	return strconv.Itoa(len(values))
}
